

target 'BuDeJie' do

   pod 'AFNetworking', '~> 3.1.0'

   pod 'MJExtension', '~> 3.0.13'

   pod 'MJRefresh', '~> 3.1.12'

   pod 'SVProgressHUD', '~> 2.0.3'

   pod 'SDWebImage', '~> 3.8.2'

   pod 'DACircularProgress', '~> 2.3.1'

  target 'BuDeJieTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BuDeJieUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
